In [2]:
import pandas as pd
data=pd.read_csv(r"C:\Users\Mega Tech\OneDrive\Desktop\amazon_sales_dataset.csv")
data.head(5)

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
0,1,4/13/2022,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52
1,2,3/12/2023,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40
2,3,9/28/2022,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28
3,4,4/17/2022,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64
4,5,3/13/2022,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  object
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [4]:
data.describe()

,order_id,product_id,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,2986.848740,252.507260,13.340700,2.999400,2.996316,249.329280,218.886566,657.331475
std,14433.901067,1156.374535,143.025544,9.850694,1.415401,1.154295,144.251981,127.317681,526.223968
min,1.000000,1000.000000,5.010000,0.000000,1.000000,1.000000,0.000000,3.530000,3.840000
25%,12500.750000,1983.000000,127.840000,5.000000,2.000000,2.000000,125.000000,109.680000,240.320000
50%,25000.500000,2983.000000,252.970000,10.000000,3.000000,3.000000,250.000000,215.805000,505.410000
75%,37500.250000,3989.000000,376.335000,20.000000,4.000000,4.000000,374.000000,322.702500,968.970000
max,50000.000000,4999.000000,499.990000,30.000000,5.000000,5.000000,499.000000,499.910000,2499.550000

In [13]:
from ydata_profiling import ProfileReport
profile=ProfileReport(data)
profile.to_notebook_iframe()

ModuleNotFoundError: No module named 'ipywidgets'

In [ ]:
!pip install ipywidgets

Requirement already satisfied: ipywidgets in C:\Users\Mega Tech\AppData\Local\Programs\Python\Python313\Lib\site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipywidgets) (9.6.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\Mega Tech\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\Mega Tech\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: colorama in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in C:\Users\Mega Tech\AppData\Roaming\Python\Python313\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)

In [ ]:
import sys
print(sys.version)
print(sys.executable)

3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
c:\Users\Mega Tech\AppData\Local\Programs\Python\Python311\python.exe